name: Bing Dorker
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: BruteForce
      run: |
        python3 main.txty
    - name: Result
      uses: actions/upload-artifact@v1
      with:
        name: list
        path: ./list.txt
